[package]
name = "helix-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
xshell.workspace = true
eyre.workspace = true
color-eyre.workspace = true
regex.workspace = true
